#!/bin/bash
# Manda a ElasticSearch lo que estás haciendo
# TODO: mandar a elasticsearch lo que estas haciendo

host=192.168.1.61 #elasticsearch host.
port=9201
hora=$(date)

while getopts ":u:h" opt; do
	case $opt in
		u)
			USER=$OPTARG
			;;
		h)
			echo "Use: now [-u username] msg"
			exit 1
			;;
	esac
done

shift; shift 

body='{ "msg" : {
        "user" : "'$USER'",
        "hora" : "'$hora'",
        "msg" : "'$@'" }}'

curl -XPUT "http://$host:$port/now" -d "$body"
