#!/bin/bash
# Manda a ElasticSearch lo que estás haciendo
# TODO: mandar a elasticsearch lo que estas haciendo

host=192.168.1.61 #elasticsearch host
port=9200
hora=$(date)

curl -XPUT 'http://$host.$port/now/msg' -d '{
	"msg" : {
		"user" : $USER
		"hora" : $hora
		"msg"  : $1
	}
}'
